# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1a2fa76f82788081375e652f68d14e44fdd0a7a2d9c9f2ca61a24775de9f688313b8d3fbca2da3b324d572483920c375f109c9c35fdd5f03ab0e8429596cb5b

test:
  secret_key_base: 28c59f5b7a1f7f464cca1000311a7a9b3e736e9ae3743cda1dd4b8ed120174f0daeb4e9c0f1138f7791824aa7fa48f0141e4758903d4b56989691ed2bd3bce5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
